objectionary/jeo-maven-plugin

- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeClass.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeMethod.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeProgram.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMetas.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMetasTest.java
In this PR I added inefficient solution for adding all the required `alias` metas.
This solution uses `xpath` on the pre-build XML. It means that instead of generation XML once, we generate it 2 times,
which is rather suboptimal, of course. I left one more puzzle to optimize it in the future.
Related to #883.
> feat(#883): Add All The Required Aliases

- README.md
- src/it/spring/verify.groovy
- src/it/variable-names/README.md
- src/it/variable-names/pom.xml
- src/main/java/org/eolang/jeo/DisassembleMojo.java
- src/main/java/org/eolang/jeo/Disassembler.java
- src/main/java/org/eolang/jeo/Disassembling.java
- src/main/java/org/eolang/jeo/representation/BytecodeRepresentation.java
- src/main/java/org/eolang/jeo/representation/asm/AsmProgram.java
- src/main/java/org/eolang/jeo/representation/asm/DisassembleMode.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeMethod.java
- src/test/java/it/JavaSourceCompilationIT.java
- src/test/java/org/eolang/jeo/representation/asm/AsmProgramTest.java
In this PR I reduced the amount of labels generated by `disassemble` goal. We just exclude all the labels that are attached to line numbers.
Also, to allow this labels, I added the following option, that can be used to include line numbers and corresponding labels:
```xml
<configuration>
<mode>debug</mode>
</configuration>
```
Related to #884.
> feat(#884): Skip Debug Labels

- src/main/java/org/eolang/jeo/Disassembling.java
- src/main/java/org/eolang/jeo/representation/BytecodeRepresentation.java
- src/main/java/org/eolang/jeo/representation/asm/DisassembleMode.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeClass.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeEntry.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeFrame.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeInstruction.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeLabel.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeLine.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeMethod.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeProgram.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeTryCatchBlock.java
- src/main/java/org/eolang/jeo/representation/bytecode/LocalVariable.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesInstruction.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMethod.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesOperand.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesTryCatch.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlInstruction.java
- src/test/java/it/JavaSourceCompilationIT.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeClassTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesInstructionTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMethodTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlFrameTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlInstructionTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlLabelTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlMethodTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlNodeTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlTryCatchEntryTest.java
At first, I thought we should combine `counting` option together with `DisassembleMode`. However, I noticed, that we can remove `counting` option completly and leave `DisassembleMode` as is without additional modifications or refactoring. This is what I've done exactly.
Closes #893.
> feat(#893): Remove 'counting' Option

- src/main/java/org/eolang/jeo/representation/directives/DirectivesComment.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesValue.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesValueTest.java
In this PR I added quotation marks for string comments.
Was:
```
java/lang/Object
```
Become:
```
"java/lang/Object"
```
Related to #901.
> feat(#901): Add Quotation Marks to String Comments

- src/main/java/org/eolang/jeo/representation/BytecodeRepresentation.java
- src/main/java/org/eolang/jeo/representation/MeasuredEo.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesProgram.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesProgramTest.java
In this PR I added one more class that tracks the time spend on transformation of a bytecode class to the corresponding XMIR representation and save this time to `/program[@ms]` attribute.
Related to #904.
> feat(#904): Track Disassembling Timing in XMIR

- src/main/java/org/eolang/jeo/representation/directives/DirectivesMetas.java
- src/test/java/org/eolang/jeo/representation/CanonicalXmirTest.java
- src/test/java/org/eolang/jeo/representation/XmirRepresentationTest.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeClassTest.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMetasTest.java
If a package is empty we just don't add `meta/head[text()='package']` to directives.
Related to #912.
> feat(#912): Do Not Add Empty Packages

- pom.xml
- src/it/annotations/pom.xml
- src/it/bytecode-to-eo/pom.xml
- src/it/custom-transformations/pom.xml
- src/it/exceptions/pom.xml
- src/it/generics/pom.xml
- src/it/jna/pom.xml
- src/it/phi-unphi/pom.xml
- src/it/spring/pom.xml
- src/it/spring/verify.groovy
- src/it/takes/pom.xml
- src/main/java/org/eolang/jeo/representation/directives/DirectivesEoObject.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesInstruction.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesJeoObject.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesValue.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeClassTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMetasTest.java
In this PR I add opcode names to their base.
For example, we used to have:
```
jeo.opcode
```
Now we have
```
jeo.opcode.ireturn
```
And we did it for all the opcodes.
Related to #917.
> feat(#917): Different Atoms For Different Opcodes

- src/main/java/org/eolang/jeo/Assembling.java
- src/main/java/org/eolang/jeo/representation/XmirRepresentation.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesSeq.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlInstruction.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlNode.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlProgram.java
- src/test/java/org/eolang/jeo/representation/XmirRepresentationTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesSeqTest.java
In this PR I optimize `disassemble/assemle` goals to speed up development.
Timings after optimization:
```
[INFO]           spring-fat/pom.xml ............................... SUCCESS (301.7 s)
[INFO]           spring-fat/pom.xml ............................... SUCCESS (313.2 s)
[INFO]           spring-fat/pom.xml ............................... SUCCESS (378.5 s)
```
As you can see, in some cases we got ~ x10 speed up.
Related to #889.
> feat(#889): Optimize Disassemble/Assemble Goals

- src/it/bytecode-to-eo/pom.xml
- src/it/bytecode-to-eo/verify.groovy
In this PR I fix the problem with `bytecode-to-eo` integration test. I print `eo` objects only on Java 11 and above.
Closes: #928.
> frat(#928): Don't Print EO if Java < 11"

- src/main/java/org/eolang/jeo/representation/XmirRepresentation.java
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlDoc.java
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlNode.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlNode.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlProgram.java
- src/test/java/org/eolang/jeo/representation/xmir/JcabiXmlDocTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlProgramTest.java
In this PR I switched from `NativeXmlDoc` usage to `JcabiXmlDoc`.
Closes: #953.
> feat(#953): Use `jcabi` Xml Implementation

- src/main/java/org/eolang/jeo/representation/VerifiedEo.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMethodParam.java
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlNode.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodParameterTest.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodParametersTest.java
In this PR I use `objectionary/lints` to verify `xmir` after `dissasseble` phase and then after `phi/unphi/unroll` phases.
Related to: #938
> feat(#938): Use `objectionary/lints` Before and After `phi/unphi`

- pom.xml
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlNode.java
In this PR I have upgradeed `objectionary/lints` library up to `0.0.31` version.
Closes: #958.
> feat(#958): Upgrade `objectionary/lints` Library

- src/main/java/org/eolang/jeo/representation/XmirRepresentation.java
- src/test/java/org/eolang/jeo/representation/XmirRepresentationTest.java
In this PR I fixed the bug related to a class name retrieval. Now, if the `metas` section is absent, we return empty package instead of throwing a runtime exception.
Related to #967.
> feat(#967): Fix the Bug Realted to Absent `metas`

- src/it/annotations/pom.xml
- src/it/bytecode-to-eo/pom.xml
- src/it/custom-transformations/pom.xml
- src/it/exceptions/pom.xml
- src/it/generics/pom.xml
- src/it/jna/pom.xml
- src/it/phi-unphi/pom.xml
- src/it/spring/pom.xml
- src/it/takes/pom.xml
- src/main/java/org/eolang/jeo/representation/directives/DirectivesValue.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlValue.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesAnnotationsTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesValueTest.java
In this PR I change the transformation method for boolean values. Long story short:
Instead of:
```xml
<o base="jeo.bool">
<o base="org.eolang.bytes">00-</o>
</o>
```
we have the following now:
```xml
<o base="org.eolang.true"/>
<o base="org.eolang.false"/>
```
Related to #977
> feat(#977): Use `org.eolang.true` and `org.eolang.false` for Boolean Values

- pom.xml
- src/it/annotations/pom.xml
- src/it/bytecode-to-eo/pom.xml
- src/it/custom-transformations/pom.xml
- src/it/exceptions/pom.xml
- src/it/generics/pom.xml
- src/it/jna/invoker.properties
- src/it/jna/pom.xml
- src/it/phi-unphi/pom.xml
- src/it/spring/pom.xml
- src/it/takes/pom.xml
- src/main/java/org/eolang/jeo/representation/directives/DirectivesProgram.java
- src/main/scripts/benchmark.groovy
In this PR I switch `jna` integration test from the `short` profile to the `full` profile.
By doing this, we enable PHI/UNPHI transformations in the test. It slightly slows down the integration test, but ensures qality.
Also, I slightly refactored `benchmark.groovy` script to switch between integration tests faster.
Closes: #999.
> feat(#999): Add PHI/UNPHI Steps to `jna` Integration Test

- src/main/java/org/eolang/jeo/representation/directives/DirectivesMetas.java
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlNode.java
In this PR I fixed several minor issues related to incorrect XMIR generated by `disassemble` goal. The only issue we are left with is `object-does-notmatch-filename`. I've added one more puzzle to close it later when we decide how to solve it:
https://github.com/objectionary/lints/issues/352
Closes: #965
> feat(#965): Fix Some XMIR Offences

- pom.xml
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMetas.java
In this PR I've updated `objectionary/lints` dependency `0.0.41` -> `0.0.42` and added `spdx` metas to all XMIR files generated by the `disassemble` goal.
Closes: #1028
> feat(#1028): Add SPDX Metas to All Generated XMIR Files

- src/it/spring-fat/pom.xml
This PR addresses issue #543 by removing the puzzle related to bytecode verification. We just can't enable bytecode verification for the 'spring-fat' integration test. I've added explanation to the comment.
Closes: #543
> feat(#543): Bytecode Verification for 'spring-fat' Integration Test

- src/it/custom-transformations/pom.xml
This pull request enables the EO Printing goal in the 'custom-transformations' integration test, which was previously disabled due to lack of support for Java 8. The necessary configurations have been uncommented to activate the  goal. Closes #619.
> feat(#619): Enable EO Printing in 'custom-transformations' integration test

- pom.xml
This pull request removes the `<parallelThreads>` configuration from the Maven Surefire and Failsafe plugins in the 'pom.xml' file to streamline the build process and exclude flaky behaviour. Closes #1044.
> fix(#1044): Remove `parallelThreads` from `pom.xml` configuration

- src/it/spring-fat/pom.xml
This pull request removes outdated comments related to the optimization of PHI printing within the `spring-fat`  integration test. The transformation is still rather long and most probably will stay the same in the future. So, to speed up the build, we can just avoid running this transformation on large number of files. Closes #633.
> chore(#633): Remove 'xmir-to-phi' transformation from 'spring-fat' integration test

- pom.xml
- src/main/java/org/eolang/jeo/representation/License.java
- src/test/java/org/eolang/jeo/representation/LicenseTest.java
This pull request enhances the `License` class by introducing thread safety with the `Synced` decorator and adds a new test to verify concurrent access. Additionally, it updates the `pom.xml` to include the `together` library for testing purposes. Closes #1051.
> test(#1051): Make `License` thread safe and add concurrent test

- src/main/java/org/eolang/jeo/representation/directives/DirectivesSeq.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMethodTest.java
This pull request refines the `DirectivesSeq` class by removing the unused random number generator. Additionally, a new test is introduced in `DirectivesMethodTest` to verify the correct generation of method body names.
Related to #1063
> fix(#1063): remove random suffix from method body name generation

- src/main/java/org/eolang/jeo/representation/directives/DirectivesValue.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlValue.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesAnnotationsTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesValueTest.java
This pull request refactors the handling of boolean objects within the `DirectivesValue` and `XmlValue` classes. Now, instead of `Φ.jeo.bool(Φ̇.false)` object, we just geneare `Φ̇.false`.  Additionally, the PR updates the corresponding test cases to align with these changes.
Related to #1060
> feat(#1060): Simplify `Φ.jeo.bool(Φ̇.false)` -> `Φ̇.false`

- src/it/phi-unphi/verify.groovy
- src/main/java/org/eolang/jeo/representation/bytecode/DataType.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesNumber.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesValue.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeObjectTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesClassPropertiesTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesFieldTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesHandleTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesValueTest.java
- src/test/java/org/eolang/jeo/representation/directives/HasMethod.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlValueTest.java
This pull request refactors the handling of integer representations in the PHI representation. It replaces the usage of `int` with `number` for a more consistent and simplified representation of integer numbers.
In other words, instead of `Φ.jeo.opcode.dload(Φ.jeo.int(24), Φ.jeo.int(1))`, we have `Φ.jeo.opcode.dload(24, 1)`
Related to #1061
> feat(#1061): Simplify integer representation to `number` type

- src/it/phi-unphi/verify.groovy
- src/main/java/org/eolang/jeo/representation/NumberedName.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeClass.java
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeMethod.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMethod.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlMethod.java
- src/test/java/org/eolang/jeo/representation/NumberedNameTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMethodTest.java
This PR changes method name generation strategy by removing encoded descriptor from the name and adds numbered suffixes to distinguish between overloaded methods. Long story short, instead of 
`j$main-%28%5BLjava%2Flang%2FString%3B%29V` now we have `j$main-2`.
Related to #1064
> feat(#1064): Method names `j$main-%28%5BLjava%2Flang%2FString%3B%29V`  -> `j$main-2`

- src/it/phi-unphi/verify.groovy
- src/main/java/org/eolang/jeo/representation/directives/DirectivesAnnotations.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesMethodParam.java
- src/main/java/org/eolang/jeo/representation/xmir/XmlParam.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodParameterTest.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodParametersTest.java
- src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesMethodParamTest.java
- src/test/java/org/eolang/jeo/representation/xmir/XmlParamTest.java
This pull request refactors the representation of method parameters in `Φ.jeo.params` to improve optimization capabilities by using structured attributes instead of encoded names. 
Before:
```
param-%5BLjava%2Flang%2FString%3B-arg0-0-0-556384129 ↦ Φ.jeo.param
```
After:
```
arg0 ↦ Φ.jeo.param(
index ↦ 0,
access ↦ 0,
type ↦ "[Ljava/lang/String;"
)
```
Related to #1062
> refactor(#1062): simplify PHI parameter representation for optimization

- .markdownlint.yml
- .typos.toml
- CODE_OF_CONDUCT.md
- README.md
- src/it/custom-transformations/src/main/java/org/eolang/jeo/Application.java
- src/it/custom-transformations/src/main/java/org/eolang/spring/package-info.java
- src/it/jna/README.md
- src/it/spring-fat/README.md
- src/main/java/org/eolang/jeo/representation/bytecode/BytecodeMethod.java
- src/main/java/org/eolang/jeo/representation/bytecode/package-info.java
- src/main/java/org/eolang/jeo/representation/directives/DirectivesValues.java
- src/test/java/org/eolang/jeo/representation/asm/AsmProgramTest.java
- src/test/java/org/eolang/jeo/representation/directives/DirectivesInstructionTest.java
- src/test/resources/maxs/MaxInterface.java
- src/test/resources/maxs/Maxs.java
This PR fixes typos in documentation and code to resolve failing `markdown-lint` and `typos` pipelines, including corrections to method names and comments.
Closes #1085
> fix(#1085): Fix typos and markdown lint errors in codebase

- pom.xml
- src/it/annotations/pom.xml
- src/it/bytecode-to-eo/pom.xml
- src/it/custom-transformations/pom.xml
- src/it/exceptions/pom.xml
- src/it/generics/pom.xml
- src/it/jna/pom.xml
- src/it/phi-unphi/pom.xml
- src/it/spring/pom.xml
- src/it/takes/pom.xml
- src/main/java/org/eolang/jeo/representation/directives/DirectivesObject.java
Updates EO language dependencies and XMIR schema references from `0.56.0` to `0.56.2` for compatibility.
Closes #1083
> build(#1083): update EO language version to 0.56.2

- .gitignore
- pom.xml
- src/main/java/org/eolang/jeo/representation/xmir/JcabiXmlNode.java
Updates `org.eolang:lints` dependency from v0.0.46 to v0.0.49 and adjusts code to use the new `Source` class instead of `Program`. Also adds Eclipse IDE files to `.gitignore`.
Closes #1069
> fix(#1069): update lints dependency to v0.0.50 and refactor validation
